# Generated by Django 2.1.2 on 2018-12-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.TextField(max_length=200)),
                ('sex', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=30)),
                ('sbu', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
