# Generated by Django 2.1.4 on 2019-03-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('sbu', models.CharField(choices=[('Administration', 'Administration'), ('Avitech', 'Avitech'), ('Devops', 'Devops'), ('Edutech', 'Edutech'), ('Engineering Operations', 'Engineering Operations'), ('Finance', 'Finance'), ('Finatech', 'Finatech'), ('Garden Data', 'Garden Data'), ('Garden Social Ventures', 'Garden Social Ventures'), ('HNI', 'HNI'), ('Legal', 'Legal'), ('Powertech', 'Powertech'), ('People Operations', 'People Operations'), ('Security', 'Security'), ('Shared Resource', 'Shared Resource'), ('Venture Garden Group', 'Venture Garden Group'), ('Vigipay', 'Vigipay')], max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Customer', 'Customer'), ('Partner', 'Partner'), ('Staff', 'Staff')], max_length=10)),
                ('company', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
