# Generated by Django 2.1.4 on 2018-12-29 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_trash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='role',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='trash',
            old_name='role',
            new_name='position',
        ),
    ]
