# Generated by Django 2.1.4 on 2018-12-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20181230_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sbu',
            field=models.CharField(choices=[[1, 'Administration'], [2, 'Avitech'], [3, 'Edutech'], [4, 'Engineering Operations'], [5, 'Finance'], [6, 'Finatech'], [7, 'Garden Data'], [8, 'Garden Social Ventures'], [9, 'HNI'], [10, 'Legal'], [11, 'Powertech'], [12, 'People Operations'], [13, 'Venture Garden Group'], [14, 'Vigipay']], max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sex',
            field=models.CharField(choices=[[1, 'Female'], [2, 'Male']], max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[[1, 'Customer'], [2, 'Partner'], [3, 'Staff']], max_length=10),
        ),
    ]
