# Generated by Django 2.1.4 on 2018-12-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20181230_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sbu',
            field=models.CharField(choices=[[1, 'Administration'], [2, 'Avitech'], [3, 'Devops'], [4, 'Edutech'], [5, 'Engineering Operations'], [6, 'Finance'], [7, 'Finatech'], [8, 'Garden Data'], [9, 'Garden Social Ventures'], [10, 'HNI'], [11, 'Legal'], [12, 'Powertech'], [13, 'People Operations'], [14, 'Venture Garden Group'], [15, 'Vigipay']], max_length=30),
        ),
    ]
