# Generated by Django 2.1.4 on 2019-02-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20190107_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='trash',
            name='company',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sbu',
            field=models.CharField(choices=[('Administration', 'Administration'), ('Avitech', 'Avitech'), ('Devops', 'Devops'), ('Edutech', 'Edutech'), ('Engineering Operations', 'Engineering Operations'), ('Finance', 'Finance'), ('Finatech', 'Finatech'), ('Garden Data', 'Garden Data'), ('Garden Social Ventures', 'Garden Social Ventures'), ('HNI', 'HNI'), ('Legal', 'Legal'), ('Powertech', 'Powertech'), ('People Operations', 'People Operations'), ('Security', 'Security'), ('Venture Garden Group', 'Venture Garden Group'), ('Vigipay', 'Vigipay')], max_length=30),
        ),
    ]
